# Generated by Django 3.1.5 on 2021-04-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Updated')),
                ('userId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainPermisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_type_id', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('update_at', models.DateField(auto_now_add=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Updated')),
                ('isCompleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('compdate', models.DateField()),
                ('userId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Sname', models.CharField(max_length=100)),
                ('Uname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('update_at', models.DateField(auto_now_add=True, verbose_name='Updated')),
                ('permisions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.mainpermisions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.users')),
            ],
        ),
    ]
